### ISSUE TITLE
lgc withdraw -> JSONRPCError: {"code":-32602,"message":"Invalid params"}

### ISSUE THREAD

**Issue by Flouse** [godwokenrises/godwoken-tests#182]
## Version
- [ghcr.io/nervosnetwork/godwoken-prebuilds:1.5-rc](https://github.com/nervosnetwork/godwoken-polyjuice/runs/8110769568?check_suite_focus=true#step:13:42)
- nervos/godwoken-web3-prebuilds:v1.6.4

## Context
https://github.com/nervosnetwork/godwoken-polyjuice/runs/8110769568?check_suite_focus=true#step:16:18

```js
(node:24401) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
chain_id: 0x[11](https://github.com/nervosnetwork/godwoken-polyjuice/runs/8110769568?check_suite_focus=true#step:16:12)6e8
/home/runner/work/godwoken-polyjuice/godwoken-polyjuice/scripts/light-godwoken-cli/dist/index.js:261629
        throw new Error("JSONRPCError: server error " + JSON.stringify(o2.error));
              ^

Error: JSONRPCError: server error {"code":-32602,"message":"Invalid params"}
    at Proxy.<anonymous> (/home/runner/work/godwoken-polyjuice/godwoken-polyjuice/scripts/light-godwoken-cli/dist/index.js:261629:[15](https://github.com/nervosnetwork/godwoken-polyjuice/runs/8110769568?check_suite_focus=true#step:16:16))
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Flouse** [comment]
# Web3 logs
```js
2022-09-01T03:43:53.694Z [info]: POST / 200 3ms @gw_get_account_id_by_script_hash
2022-09-01T03:43:53.700Z [error]: JSONRPC Server Error: [bound get_nonce] RpcError: Invalid params RpcError: Invalid params
    at Object.parseGwRpcError (/godwoken-web3/packages/api-server/lib/methods/gw-error.js:199:15)
    at Gw.get_nonce (/godwoken-web3/packages/api-server/lib/methods/modules/gw.js:180:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /godwoken-web3/packages/api-server/lib/methods/validator.js:33:24
```
