### ISSUE TITLE
testcase Error: failed to get consistent fee data (operation="signer.getFeeData", code=UNSUPPORTED_OPERATION

### ISSUE THREAD

**Issue by Flouse** [godwokenrises/godwoken-tests#37]
https://github.com/nervosnetwork/godwoken-tests/runs/4301298436?check_suite_focus=true#step:19:42

```log
$ /home/runner/work/godwoken-tests/godwoken-tests/testcases/godwoken-polyjuice-compatibility-examples/node_modules/.bin/ts-node ./scripts/multi-sign-wallet.ts
Running: Initialize Godwoken account for 0xcbBcD4691175e20eB71106F7ec5FDb991044d842 by deposit
    It may take a few minutes...
    Initialized, id: 4
Running: Initialize Godwoken account for 0xc0bf5e5072294950F1ac54989b58BF5ebb020b28 by deposit
    It may take a few minutes...
    Initialized, id: 5
Deployer address: 0x6DaF63D8411D6E23552658E3cFb48416A6A2CA78
Deployer godwoken address: 0xdfb94d6794165b96668b4308607afc05790dc211
Running: Load transaction history multi-sign-wallet-gwk-devnet.json
    New history created
Running transaction: Deploy WalletSimple
err Error: failed to get consistent fee data (operation="signer.getFeeData", code=UNSUPPORTED_OPERATION, version=abstract-signer/5.4.0)
    at Logger.makeError (/home/runner/work/godwoken-tests/godwoken-tests/testcases/godwoken-polyjuice-compatibility-examples/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/home/runner/work/godwoken-tests/godwoken-tests/testcases/godwoken-polyjuice-compatibility-examples/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at PolyjuiceWallet.<anonymous> (/home/runner/work/godwoken-tests/godwoken-tests/testcases/godwoken-polyjuice-compatibility-examples/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:278:28)
    at step (/home/runner/work/godwoken-tests/godwoken-tests/testcases/godwoken-polyjuice-compatibility-examples/node_modules/@ethersproject/abstract-signer/lib/index.js:48:23)
    at Object.next (/home/runner/work/godwoken-tests/godwoken-tests/testcases/godwoken-polyjuice-compatibility-examples/node_modules/@ethersproject/abstract-signer/lib/index.js:29:53)
    at fulfilled (/home/runner/work/godwoken-tests/godwoken-tests/testcases/godwoken-polyjuice-compatibility-examples/node_modules/@ethersproject/abstract-signer/lib/index.js:20:58) {
  reason: 'failed to get consistent fee data',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'signer.getFeeData'
}
error Command failed with exit code 1.
```

**Comment by Flouse** [comment]
outdated
